### ISSUE TITLE
Incorrect python dependency for pyaml >=23.5.7

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/pyaml-feedstock#23]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

On conda-forge, this package lists python >=3.6 as a dependency.  However, I installed pyaml 23.5.7 in a python 3.7 environment, and I got an error when trying to import it, as it uses python 3.8 syntax.  Additionally, I see in the project's pyproject.toml file that it has increased its required python version to >=3.8.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by thewchan** [comment]
Thanks I'm addressing this in https://github.com/conda-forge/pyaml-feedstock/pull/24
